name: infra-docker-ec2-deploy

on:
  push:
    branches: [ master ]

jobs:

  infra:
    name: Terraform Apply (infra)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Terraform
        working-directory: Infra
        run: |
          apt-get update -y
          apt-get install -y wget unzip
          wget https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
          unzip terraform_1.5.7_linux_amd64.zip
          mv terraform /usr/local/bin/

      - name: Terraform Init & Apply
        working-directory: Infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          TF_BUCKET: ${{ secrets.TF_BUCKET }}
          TF_KEY: ${{ secrets.TF_KEY }}
          TF_LOCK_TABLE: ${{ secrets.TF_LOCK_TABLE }}
        run: |
          terraform init \
            -backend-config="bucket=${TF_BUCKET}" \
            -backend-config="key=${TF_KEY}" \
            -backend-config="region=${AWS_REGION}" \
            -backend-config="dynamodb_table=${TF_LOCK_TABLE}"

          terraform apply -auto-approve


  build_and_push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: infra

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
        run: echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin

      - name: Build image
        run: docker build -t myapp:latest .

      - name: Tag & Push
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          docker tag myapp:latest ${DOCKER_USER}/myapp:latest
          docker push ${DOCKER_USER}/myapp:latest


  deploy:
    name: Deploy to EC2 (SSH)
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install AWS CLI
        run: |
          apt-get update -y
          apt-get install -y awscli

      - name: Get EC2 Public IP From AWS
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          EC2_IP=$(aws ec2 describe-instances \
            --filters "Name=tag:Name,Values=myapp-server" \
            --query "Reservations[].Instances[].PublicIpAddress" \
            --output text \
            --region $AWS_REGION)

          echo "$EC2_IP" > ec2_ip.txt
          echo "EC2_IP = $EC2_IP"

      - name: Add SSH key
        env:
          EC2_SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$EC2_SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy App on EC2
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
        run: |
          EC2_IP=$(cat ec2_ip.txt)

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ubuntu@$EC2_IP <<EOF
            sudo docker stop myapp || true
            sudo docker rm myapp || true
            sudo docker pull ${DOCKER_USER}/myapp:latest
            sudo docker run -d --name myapp -p 8080:8080 ${DOCKER_USER}/myapp:latest
          EOF
