  app:
    runs-on: docker
    needs: infra
    name: Deploy Application

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        run: |
          echo ${{ secrets.DOCKER_PASS }} | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t myapp:latest .

      - name: Tag Image
        run: |
          docker tag myapp:latest ${{ secrets.DOCKER_USER }}/myapp:latest

      - name: Push Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USER }}/myapp:latest

      - name: Stop Old Container
        run: |
          docker stop myapp || true
          docker rm myapp || true

      - name: Start New Container
        run: |
          docker run -d \
            --name myapp \
            -p 8080:8080 \
            ${{ secrets.DOCKER_USER }}/myapp:latest
